### ISSUE TITLE
Read a wishlist

### ISSUE THREAD

**Issue by brentdur** [nyu-devops-golf-team/wishlist#2] opened 2017-10-04 19:17 UTC
**As a** customer
**I need** to be able to retrieve a single wishlist by its id
**So that** I can get the product ids and name of the wishlist

**Assumptions:** 
* the list returned will not be one that's persisted

**Acceptance Criteria:**
```
Given that I have a wishlist id
When I make a request with that wishlist id
Then i get a wishlist with a name, id, and list of products
```

**Comment by DB3619** [comment] 2017-10-15 19:33
This issue looks to me like a duplicate of querying a wishlist by name : Issue 4. The wishlist ID is maintained by us for internal use. So the customer has no information about the wishlist ID

**Comment by aashishdugar** [comment] 2017-10-16 21:45
It does seem like a duplicate. Looks like pretty much the "get" method all over again.

**Comment by DB3619** [comment] 2017-10-16 21:45
We will duplicate it.

**Closed** 2017-10-18 19:31 UTC
Labels: wanted
